### ISSUE TITLE
Route not deleted in Deploying Applications From Images step 4 of 6

### ISSUE THREAD

**Issue by jsutton** [openshift-evangelists/intro-katacoda#118]
After running
`oc delete all --selector app=blog-django-py`
All resources are deleted except the route
```shell
oc delete all --selector app=blog-django-py
imagestream "blog-django-py" deleted
deploymentconfig "blog-django-py" deleted
service "blog-django-py" deleted
pod "blog-django-py-1-594d2" deleted
$ oc get all -o name
routes/blog-django-py
$ oc delete all --selector app=blog-django-py
No resources found
$ oc get all -o name
routes/blog-django-py
$ oc delete route/blog-django-py
route "blog-django-py" deleted
```
The same behavior does not occur when creating the route from the CLI.
The output of `oc get all` is the same in both cases.
```
$ oc get all -o name
imagestreams/blog-django-py
deploymentconfigs/blog-django-py
replicationcontrollers/blog-django-py-1
routes/blog-django-py
services/blog-django-py
pods/blog-django-py-1-qnggk
```
When deleting the route created from the CLI, the command performs the expected operations
```
$ oc delete all --selector app=blog-django-py
imagestream "blog-django-py" deleted
deploymentconfig "blog-django-py" deleted
route "blog-django-py" deleted
service "blog-django-py" deleted
pod "blog-django-py-1-xkt91" deleted
```

**Comment by GrahamDumpleton** [comment]
The issue relates to a problem in OpenShift 3.6 web console where in the version used it isn't applying an ``app=blog-django-py`` label automatically when creating a route.

This is why in step 3 it says:

> Before creating the route, ensure that the app label is listed with value blog-django-py. Add this label if not present as we will be using it later.

This is to compensate for fact the web console isn't adding it and is asking you to do it.

So it is subtly covering up for an issue in web console in 3.6. 

I believe this issue is fixed in newer OpenShift version, but asking you to ensure label created in step 3 was best we could do at the time.

**Comment by jsutton** [comment]
Understood. I totally missed that direction. I was too busy playing around with the CLI. Thank you.
