### ISSUE TITLE
Have a clean way to load a template as part of the init

### ISSUE THREAD

**Issue by thesteve0** [openshift-evangelists/intro-katacoda#19]

**Comment by BenHall** [comment]
Here is the docs page on the topic - https://katacoda.com/docs/scenarios/pre-init

The index.json will have a new assets node. This will upload files from a assets directory to the environment automatically. So instead of using env-init (https://github.com/openshift-evangelists/intro-katacoda/blob/master/intro-openshift/deploying-images/env-init.sh#L1-L13) it will be defined in index.json.

For example:

```
  "assets": {
    "host01": [
      {
        "file": "route.json",
        "target": "~/"
      }
    ]
  }
```

This is live and being used by Katacoda but let me migrate the existing scenarios after Kubecon and I can test to make sure it works effectively.
