### ISSUE TITLE
Upgrade Openshift Origin 1.5

### ISSUE THREAD

**Issue by BenHall** [openshift-evangelists/intro-katacoda#27]
Upgrade Openshift to Origin 1.5

**Comment by GrahamDumpleton** [comment]
Will need warning on when switch occurs as will need to possibly update some screen shots and descriptions as behaviour of web console has change a little in certain areas, such as display of logs for pods. The new version will automatically follow logs in the web console rather than you needing to click on follow.

**Comment by BenHall** [comment]
Good to know, thank you. I'll build the environment and make it available for testing without effecting the current site.

**Comment by BenHall** [comment]
I'll email the team access to the development environment with the 1.5 build for testing.
