### ISSUE TITLE
Could not open session

### ISSUE THREAD

**Issue by maicolcantagallo** [openshift-evangelists/intro-katacoda#63]
Hi,
when restart application return error "could not open session" and application is not ready

Why?

Thanks

**Comment by GrahamDumpleton** [comment]
If you are having an issue with learn.openshift.com, can you be more specific as to which learning scenario you were working through and at what point you had any issue. We can then check whether everything is okay.

Due to load on the system, we sometimes do have intermittent issues, but starting over the scenario and trying again usually fixes the issue and it will all work again.

**Comment by maicolcantagallo** [comment]
My application is on https://openshift.redhat.com. When i try to restart application show this error. And application doesn't works.

**Comment by GrahamDumpleton** [comment]
This Git repository is for the interactive learning environment available at learn.openshift.com. It is not for querying about problems with any applications you have hosted with OpenShift 2 or 3 environments.

If you are having issues with these environments, you can find the appropriate forums through any support links in the web console or site for the environment you are using.

If using OpenShift 2, ensure you have read:

* https://blog.openshift.com/migrate-to-v3-v2-eol/

This along with a number of emails users of that environment were sent, talks about the shutdown of OpenShift 2 and the need to move to OpenShift 3.
