### ISSUE TITLE
Deploy OCP metrics scenario

### ISSUE THREAD

**Issue by e-minguez** [openshift-evangelists/intro-katacoda#70]
As part of this trello card https://trello.com/c/Gxw6cLpb/1000-5-katacoda-new-scenarios I'm working on a scenario for users to enable and use OCP metrics.

**Comment by jorgemoralespou** [comment]
@e-minguez, given that metrics will change much when we move to Prometheus, if encourage to first show scenarios that Remy on the capabilities being available (hpa, ...) rather than on the install part. Then, I think we can discuss making a first scenario on installing OpenShift via ansible, and then maybe extending that installation. I think this makes more sense given the state of things.

**Comment by e-minguez** [comment]
Will do
