### ISSUE TITLE
No java compiler (javac) in openshift-middleware image

### ISSUE THREAD

**Issue by tqvarnst** [openshift-evangelists/intro-katacoda#76]
There is only a JRE and not a JDK available in the image, which makes our builds fail.

**Comment by tqvarnst** [comment]
A fix would be to change the intro-katacoda/environments/openshift-middleware/scripts/middleware.sh line 8 to:

`yum install java-1.8.0-openjdk-devel -y`

instead of it's current value:

`yum install java-1.8.0-openjdk -y`

**Comment by BenHall** [comment]
Thanks. Rebuilding but may take a while before it's pushed out across all the nodes.

**Comment by thesteve0** [comment]
Go ahead and do it.

Do you also want to put the maven
.m2 stuff in now as well. There are probably also some docker pulls we want
to add as well for Christina

It will trigger an automatic rebuild once you do. The build will probably
take a while.

Coming at you from my phone, please excuse typos, poor grammar, curtness,
and dashing good looks

On Nov 20, 2017 5:42 AM, "Thomas Qvarnström" <notifications@github.com>
wrote:

A fix would be to change the intro-katacoda/environments/
openshift-middleware/scripts/middleware.sh line 8 to:

yum install java-1.8.0-openjdk-devel -y

instead of it's current value:

yum install java-1.8.0-openjdk -y

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/openshift-evangelists/intro-katacoda/issues/76#issuecomment-345698760>,
or mute the thread

**Comment by BenHall** [comment]
If we can do the .m2 changes now that would be great!!  :)

**Comment by tqvarnst** [comment]
We need one more day to get the setup and project code sorted so let's do this change first

**Comment by BenHall** [comment]
```
$ javac -version
javac 1.8.0_151
```

This is only on staging environment (https://host02.katacoda.com) as per Trello discussion.
